Repository sudiptob2/leet-easy, pull requests merged in 2022-10, with the labels that each got.

#34 add retry logic of 3 attempts for connecting to leetcode, sleep for 1…
  leeteasy/constant.py
  leeteasy/services/request_handler.py
Labels: hacktoberfest-accepted, hacktoberfest

#45 add examples in CONTRIBUTING.md
  README.md
  docs/CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#46 Gh test
  .github/workflows/test.yml
Labels: hacktoberfest-accepted, hacktoberfest

#37 [#31] test: add tests for TimeValidator
  tests/test_validators/__init__.py
  tests/test_validators/test_time_validator.py
Labels: hacktoberfest-accepted, hacktoberfest

#50 fixed notifications if the user's machine was powered on after the scheduled time had past
  leeteasy/__main__.py
Labels: hacktoberfest-accepted, hacktoberfest

#52 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted
